// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: NWScript/nwnx.proto

#include "NWScript/nwnx.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace NWNX4 {
namespace HookHorror {
namespace Proto {
namespace NWScript {
constexpr NWNXGetIntRequest::NWNXGetIntRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sfunction_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sparam1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , nparam2_(0){}
struct NWNXGetIntRequestDefaultTypeInternal {
  constexpr NWNXGetIntRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NWNXGetIntRequestDefaultTypeInternal() {}
  union {
    NWNXGetIntRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NWNXGetIntRequestDefaultTypeInternal _NWNXGetIntRequest_default_instance_;
constexpr NWNXSetIntRequest::NWNXSetIntRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sfunction_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sparam1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , nparam2_(0)
  , nvalue_(0){}
struct NWNXSetIntRequestDefaultTypeInternal {
  constexpr NWNXSetIntRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NWNXSetIntRequestDefaultTypeInternal() {}
  union {
    NWNXSetIntRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NWNXSetIntRequestDefaultTypeInternal _NWNXSetIntRequest_default_instance_;
constexpr NWNXGetFloatRequest::NWNXGetFloatRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sfunction_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sparam1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , nparam2_(0){}
struct NWNXGetFloatRequestDefaultTypeInternal {
  constexpr NWNXGetFloatRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NWNXGetFloatRequestDefaultTypeInternal() {}
  union {
    NWNXGetFloatRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NWNXGetFloatRequestDefaultTypeInternal _NWNXGetFloatRequest_default_instance_;
constexpr NWNXSetFloatRequest::NWNXSetFloatRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sfunction_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sparam1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , nparam2_(0)
  , fvalue_(0){}
struct NWNXSetFloatRequestDefaultTypeInternal {
  constexpr NWNXSetFloatRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NWNXSetFloatRequestDefaultTypeInternal() {}
  union {
    NWNXSetFloatRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NWNXSetFloatRequestDefaultTypeInternal _NWNXSetFloatRequest_default_instance_;
constexpr NWNXGetStringRequest::NWNXGetStringRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sfunction_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sparam1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , nparam2_(0){}
struct NWNXGetStringRequestDefaultTypeInternal {
  constexpr NWNXGetStringRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NWNXGetStringRequestDefaultTypeInternal() {}
  union {
    NWNXGetStringRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NWNXGetStringRequestDefaultTypeInternal _NWNXGetStringRequest_default_instance_;
constexpr NWNXSetStringRequest::NWNXSetStringRequest(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : sfunction_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , sparam1_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , svalue_(&::PROTOBUF_NAMESPACE_ID::internal::fixed_address_empty_string)
  , nparam2_(0){}
struct NWNXSetStringRequestDefaultTypeInternal {
  constexpr NWNXSetStringRequestDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~NWNXSetStringRequestDefaultTypeInternal() {}
  union {
    NWNXSetStringRequest _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT NWNXSetStringRequestDefaultTypeInternal _NWNXSetStringRequest_default_instance_;
}  // namespace NWScript
}  // namespace Proto
}  // namespace HookHorror
}  // namespace NWNX4
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_NWScript_2fnwnx_2eproto[6];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_NWScript_2fnwnx_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_NWScript_2fnwnx_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_NWScript_2fnwnx_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, sfunction_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, sparam1_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, nparam2_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, sfunction_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, sparam1_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, nparam2_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, nvalue_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, sfunction_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, sparam1_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, nparam2_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, sfunction_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, sparam1_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, nparam2_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, fvalue_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, sfunction_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, sparam1_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, nparam2_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, sfunction_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, sparam1_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, nparam2_),
  PROTOBUF_FIELD_OFFSET(::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, svalue_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest)},
  { 8, -1, sizeof(::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest)},
  { 17, -1, sizeof(::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest)},
  { 25, -1, sizeof(::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest)},
  { 34, -1, sizeof(::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest)},
  { 42, -1, sizeof(::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NWNX4::HookHorror::Proto::NWScript::_NWNXGetIntRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NWNX4::HookHorror::Proto::NWScript::_NWNXSetIntRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NWNX4::HookHorror::Proto::NWScript::_NWNXGetFloatRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NWNX4::HookHorror::Proto::NWScript::_NWNXSetFloatRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NWNX4::HookHorror::Proto::NWScript::_NWNXGetStringRequest_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::NWNX4::HookHorror::Proto::NWScript::_NWNXSetStringRequest_default_instance_),
};

const char descriptor_table_protodef_NWScript_2fnwnx_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\023NWScript/nwnx.proto\022\037NWNX4.HookHorror."
  "Proto.NWScript\032\024NWScript/types.proto\"H\n\021"
  "NWNXGetIntRequest\022\021\n\tsFunction\030\001 \001(\t\022\017\n\007"
  "sParam1\030\002 \001(\t\022\017\n\007nParam2\030\003 \001(\005\"X\n\021NWNXSe"
  "tIntRequest\022\021\n\tsFunction\030\001 \001(\t\022\017\n\007sParam"
  "1\030\002 \001(\t\022\017\n\007nParam2\030\003 \001(\005\022\016\n\006nValue\030\004 \001(\005"
  "\"J\n\023NWNXGetFloatRequest\022\021\n\tsFunction\030\001 \001"
  "(\t\022\017\n\007sParam1\030\002 \001(\t\022\017\n\007nParam2\030\003 \001(\005\"Z\n\023"
  "NWNXSetFloatRequest\022\021\n\tsFunction\030\001 \001(\t\022\017"
  "\n\007sParam1\030\002 \001(\t\022\017\n\007nParam2\030\003 \001(\005\022\016\n\006fVal"
  "ue\030\004 \001(\002\"K\n\024NWNXGetStringRequest\022\021\n\tsFun"
  "ction\030\001 \001(\t\022\017\n\007sParam1\030\002 \001(\t\022\017\n\007nParam2\030"
  "\003 \001(\005\"[\n\024NWNXSetStringRequest\022\021\n\tsFuncti"
  "on\030\001 \001(\t\022\017\n\007sParam1\030\002 \001(\t\022\017\n\007nParam2\030\003 \001"
  "(\005\022\016\n\006sValue\030\004 \001(\t2\231\005\n\013NWNXService\022f\n\nNW"
  "NXGetInt\0222.NWNX4.HookHorror.Proto.NWScri"
  "pt.NWNXGetIntRequest\032$.NWNX4.HookHorror."
  "Proto.NWScript.Int\022g\n\nNWNXSetInt\0222.NWNX4"
  ".HookHorror.Proto.NWScript.NWNXSetIntReq"
  "uest\032%.NWNX4.HookHorror.Proto.NWScript.V"
  "oid\022l\n\014NWNXGetFloat\0224.NWNX4.HookHorror.P"
  "roto.NWScript.NWNXGetFloatRequest\032&.NWNX"
  "4.HookHorror.Proto.NWScript.Float\022k\n\014NWN"
  "XSetFloat\0224.NWNX4.HookHorror.Proto.NWScr"
  "ipt.NWNXSetFloatRequest\032%.NWNX4.HookHorr"
  "or.Proto.NWScript.Void\022o\n\rNWNXGetString\022"
  "5.NWNX4.HookHorror.Proto.NWScript.NWNXGe"
  "tStringRequest\032\'.NWNX4.HookHorror.Proto."
  "NWScript.String\022m\n\rNWNXSetString\0225.NWNX4"
  ".HookHorror.Proto.NWScript.NWNXSetString"
  "Request\032%.NWNX4.HookHorror.Proto.NWScrip"
  "t.Voidb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_NWScript_2fnwnx_2eproto_deps[1] = {
  &::descriptor_table_NWScript_2ftypes_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_NWScript_2fnwnx_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_NWScript_2fnwnx_2eproto = {
  false, false, 1254, descriptor_table_protodef_NWScript_2fnwnx_2eproto, "NWScript/nwnx.proto", 
  &descriptor_table_NWScript_2fnwnx_2eproto_once, descriptor_table_NWScript_2fnwnx_2eproto_deps, 1, 6,
  schemas, file_default_instances, TableStruct_NWScript_2fnwnx_2eproto::offsets,
  file_level_metadata_NWScript_2fnwnx_2eproto, file_level_enum_descriptors_NWScript_2fnwnx_2eproto, file_level_service_descriptors_NWScript_2fnwnx_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_NWScript_2fnwnx_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_NWScript_2fnwnx_2eproto);
  return descriptor_table_NWScript_2fnwnx_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_NWScript_2fnwnx_2eproto(&descriptor_table_NWScript_2fnwnx_2eproto);
namespace NWNX4 {
namespace HookHorror {
namespace Proto {
namespace NWScript {

// ===================================================================

class NWNXGetIntRequest::_Internal {
 public:
};

NWNXGetIntRequest::NWNXGetIntRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
}
NWNXGetIntRequest::NWNXGetIntRequest(const NWNXGetIntRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sfunction().empty()) {
    sfunction_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sfunction(), 
      GetArena());
  }
  sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sparam1().empty()) {
    sparam1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sparam1(), 
      GetArena());
  }
  nparam2_ = from.nparam2_;
  // @@protoc_insertion_point(copy_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
}

void NWNXGetIntRequest::SharedCtor() {
sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
nparam2_ = 0;
}

NWNXGetIntRequest::~NWNXGetIntRequest() {
  // @@protoc_insertion_point(destructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NWNXGetIntRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  sfunction_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sparam1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NWNXGetIntRequest::ArenaDtor(void* object) {
  NWNXGetIntRequest* _this = reinterpret_cast< NWNXGetIntRequest* >(object);
  (void)_this;
}
void NWNXGetIntRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NWNXGetIntRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NWNXGetIntRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sfunction_.ClearToEmpty();
  sparam1_.ClearToEmpty();
  nparam2_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NWNXGetIntRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string sFunction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_sfunction();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest.sFunction"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sParam1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sparam1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest.sParam1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nParam2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          nparam2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NWNXGetIntRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sfunction().data(), static_cast<int>(this->_internal_sfunction().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest.sFunction");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sfunction(), target);
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sparam1().data(), static_cast<int>(this->_internal_sparam1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest.sParam1");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sparam1(), target);
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_nparam2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  return target;
}

size_t NWNXGetIntRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sfunction());
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sparam1());
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nparam2());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NWNXGetIntRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NWNXGetIntRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NWNXGetIntRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
    MergeFrom(*source);
  }
}

void NWNXGetIntRequest::MergeFrom(const NWNXGetIntRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sfunction().size() > 0) {
    _internal_set_sfunction(from._internal_sfunction());
  }
  if (from.sparam1().size() > 0) {
    _internal_set_sparam1(from._internal_sparam1());
  }
  if (from.nparam2() != 0) {
    _internal_set_nparam2(from._internal_nparam2());
  }
}

void NWNXGetIntRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NWNXGetIntRequest::CopyFrom(const NWNXGetIntRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetIntRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NWNXGetIntRequest::IsInitialized() const {
  return true;
}

void NWNXGetIntRequest::InternalSwap(NWNXGetIntRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  sfunction_.Swap(&other->sfunction_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  sparam1_.Swap(&other->sparam1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(nparam2_, other->nparam2_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NWNXGetIntRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NWNXSetIntRequest::_Internal {
 public:
};

NWNXSetIntRequest::NWNXSetIntRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
}
NWNXSetIntRequest::NWNXSetIntRequest(const NWNXSetIntRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sfunction().empty()) {
    sfunction_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sfunction(), 
      GetArena());
  }
  sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sparam1().empty()) {
    sparam1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sparam1(), 
      GetArena());
  }
  ::memcpy(&nparam2_, &from.nparam2_,
    static_cast<size_t>(reinterpret_cast<char*>(&nvalue_) -
    reinterpret_cast<char*>(&nparam2_)) + sizeof(nvalue_));
  // @@protoc_insertion_point(copy_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
}

void NWNXSetIntRequest::SharedCtor() {
sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&nparam2_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&nvalue_) -
    reinterpret_cast<char*>(&nparam2_)) + sizeof(nvalue_));
}

NWNXSetIntRequest::~NWNXSetIntRequest() {
  // @@protoc_insertion_point(destructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NWNXSetIntRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  sfunction_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sparam1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NWNXSetIntRequest::ArenaDtor(void* object) {
  NWNXSetIntRequest* _this = reinterpret_cast< NWNXSetIntRequest* >(object);
  (void)_this;
}
void NWNXSetIntRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NWNXSetIntRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NWNXSetIntRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sfunction_.ClearToEmpty();
  sparam1_.ClearToEmpty();
  ::memset(&nparam2_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&nvalue_) -
      reinterpret_cast<char*>(&nparam2_)) + sizeof(nvalue_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NWNXSetIntRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string sFunction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_sfunction();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest.sFunction"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sParam1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sparam1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest.sParam1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nParam2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          nparam2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nValue = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 32)) {
          nvalue_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NWNXSetIntRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sfunction().data(), static_cast<int>(this->_internal_sfunction().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest.sFunction");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sfunction(), target);
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sparam1().data(), static_cast<int>(this->_internal_sparam1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest.sParam1");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sparam1(), target);
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_nparam2(), target);
  }

  // int32 nValue = 4;
  if (this->nvalue() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(4, this->_internal_nvalue(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  return target;
}

size_t NWNXSetIntRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sfunction());
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sparam1());
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nparam2());
  }

  // int32 nValue = 4;
  if (this->nvalue() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nvalue());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NWNXSetIntRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NWNXSetIntRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NWNXSetIntRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
    MergeFrom(*source);
  }
}

void NWNXSetIntRequest::MergeFrom(const NWNXSetIntRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sfunction().size() > 0) {
    _internal_set_sfunction(from._internal_sfunction());
  }
  if (from.sparam1().size() > 0) {
    _internal_set_sparam1(from._internal_sparam1());
  }
  if (from.nparam2() != 0) {
    _internal_set_nparam2(from._internal_nparam2());
  }
  if (from.nvalue() != 0) {
    _internal_set_nvalue(from._internal_nvalue());
  }
}

void NWNXSetIntRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NWNXSetIntRequest::CopyFrom(const NWNXSetIntRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetIntRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NWNXSetIntRequest::IsInitialized() const {
  return true;
}

void NWNXSetIntRequest::InternalSwap(NWNXSetIntRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  sfunction_.Swap(&other->sfunction_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  sparam1_.Swap(&other->sparam1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NWNXSetIntRequest, nvalue_)
      + sizeof(NWNXSetIntRequest::nvalue_)
      - PROTOBUF_FIELD_OFFSET(NWNXSetIntRequest, nparam2_)>(
          reinterpret_cast<char*>(&nparam2_),
          reinterpret_cast<char*>(&other->nparam2_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NWNXSetIntRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NWNXGetFloatRequest::_Internal {
 public:
};

NWNXGetFloatRequest::NWNXGetFloatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
}
NWNXGetFloatRequest::NWNXGetFloatRequest(const NWNXGetFloatRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sfunction().empty()) {
    sfunction_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sfunction(), 
      GetArena());
  }
  sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sparam1().empty()) {
    sparam1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sparam1(), 
      GetArena());
  }
  nparam2_ = from.nparam2_;
  // @@protoc_insertion_point(copy_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
}

void NWNXGetFloatRequest::SharedCtor() {
sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
nparam2_ = 0;
}

NWNXGetFloatRequest::~NWNXGetFloatRequest() {
  // @@protoc_insertion_point(destructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NWNXGetFloatRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  sfunction_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sparam1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NWNXGetFloatRequest::ArenaDtor(void* object) {
  NWNXGetFloatRequest* _this = reinterpret_cast< NWNXGetFloatRequest* >(object);
  (void)_this;
}
void NWNXGetFloatRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NWNXGetFloatRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NWNXGetFloatRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sfunction_.ClearToEmpty();
  sparam1_.ClearToEmpty();
  nparam2_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NWNXGetFloatRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string sFunction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_sfunction();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest.sFunction"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sParam1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sparam1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest.sParam1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nParam2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          nparam2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NWNXGetFloatRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sfunction().data(), static_cast<int>(this->_internal_sfunction().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest.sFunction");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sfunction(), target);
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sparam1().data(), static_cast<int>(this->_internal_sparam1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest.sParam1");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sparam1(), target);
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_nparam2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  return target;
}

size_t NWNXGetFloatRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sfunction());
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sparam1());
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nparam2());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NWNXGetFloatRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NWNXGetFloatRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NWNXGetFloatRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
    MergeFrom(*source);
  }
}

void NWNXGetFloatRequest::MergeFrom(const NWNXGetFloatRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sfunction().size() > 0) {
    _internal_set_sfunction(from._internal_sfunction());
  }
  if (from.sparam1().size() > 0) {
    _internal_set_sparam1(from._internal_sparam1());
  }
  if (from.nparam2() != 0) {
    _internal_set_nparam2(from._internal_nparam2());
  }
}

void NWNXGetFloatRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NWNXGetFloatRequest::CopyFrom(const NWNXGetFloatRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetFloatRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NWNXGetFloatRequest::IsInitialized() const {
  return true;
}

void NWNXGetFloatRequest::InternalSwap(NWNXGetFloatRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  sfunction_.Swap(&other->sfunction_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  sparam1_.Swap(&other->sparam1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(nparam2_, other->nparam2_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NWNXGetFloatRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NWNXSetFloatRequest::_Internal {
 public:
};

NWNXSetFloatRequest::NWNXSetFloatRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
}
NWNXSetFloatRequest::NWNXSetFloatRequest(const NWNXSetFloatRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sfunction().empty()) {
    sfunction_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sfunction(), 
      GetArena());
  }
  sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sparam1().empty()) {
    sparam1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sparam1(), 
      GetArena());
  }
  ::memcpy(&nparam2_, &from.nparam2_,
    static_cast<size_t>(reinterpret_cast<char*>(&fvalue_) -
    reinterpret_cast<char*>(&nparam2_)) + sizeof(fvalue_));
  // @@protoc_insertion_point(copy_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
}

void NWNXSetFloatRequest::SharedCtor() {
sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
::memset(reinterpret_cast<char*>(this) + static_cast<size_t>(
    reinterpret_cast<char*>(&nparam2_) - reinterpret_cast<char*>(this)),
    0, static_cast<size_t>(reinterpret_cast<char*>(&fvalue_) -
    reinterpret_cast<char*>(&nparam2_)) + sizeof(fvalue_));
}

NWNXSetFloatRequest::~NWNXSetFloatRequest() {
  // @@protoc_insertion_point(destructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NWNXSetFloatRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  sfunction_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sparam1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NWNXSetFloatRequest::ArenaDtor(void* object) {
  NWNXSetFloatRequest* _this = reinterpret_cast< NWNXSetFloatRequest* >(object);
  (void)_this;
}
void NWNXSetFloatRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NWNXSetFloatRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NWNXSetFloatRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sfunction_.ClearToEmpty();
  sparam1_.ClearToEmpty();
  ::memset(&nparam2_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&fvalue_) -
      reinterpret_cast<char*>(&nparam2_)) + sizeof(fvalue_));
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NWNXSetFloatRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string sFunction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_sfunction();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest.sFunction"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sParam1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sparam1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest.sParam1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nParam2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          nparam2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float fValue = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          fvalue_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NWNXSetFloatRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sfunction().data(), static_cast<int>(this->_internal_sfunction().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest.sFunction");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sfunction(), target);
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sparam1().data(), static_cast<int>(this->_internal_sparam1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest.sParam1");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sparam1(), target);
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_nparam2(), target);
  }

  // float fValue = 4;
  if (!(this->fvalue() <= 0 && this->fvalue() >= 0)) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_fvalue(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  return target;
}

size_t NWNXSetFloatRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sfunction());
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sparam1());
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nparam2());
  }

  // float fValue = 4;
  if (!(this->fvalue() <= 0 && this->fvalue() >= 0)) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NWNXSetFloatRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NWNXSetFloatRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NWNXSetFloatRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
    MergeFrom(*source);
  }
}

void NWNXSetFloatRequest::MergeFrom(const NWNXSetFloatRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sfunction().size() > 0) {
    _internal_set_sfunction(from._internal_sfunction());
  }
  if (from.sparam1().size() > 0) {
    _internal_set_sparam1(from._internal_sparam1());
  }
  if (from.nparam2() != 0) {
    _internal_set_nparam2(from._internal_nparam2());
  }
  if (!(from.fvalue() <= 0 && from.fvalue() >= 0)) {
    _internal_set_fvalue(from._internal_fvalue());
  }
}

void NWNXSetFloatRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NWNXSetFloatRequest::CopyFrom(const NWNXSetFloatRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetFloatRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NWNXSetFloatRequest::IsInitialized() const {
  return true;
}

void NWNXSetFloatRequest::InternalSwap(NWNXSetFloatRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  sfunction_.Swap(&other->sfunction_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  sparam1_.Swap(&other->sparam1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(NWNXSetFloatRequest, fvalue_)
      + sizeof(NWNXSetFloatRequest::fvalue_)
      - PROTOBUF_FIELD_OFFSET(NWNXSetFloatRequest, nparam2_)>(
          reinterpret_cast<char*>(&nparam2_),
          reinterpret_cast<char*>(&other->nparam2_));
}

::PROTOBUF_NAMESPACE_ID::Metadata NWNXSetFloatRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NWNXGetStringRequest::_Internal {
 public:
};

NWNXGetStringRequest::NWNXGetStringRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
}
NWNXGetStringRequest::NWNXGetStringRequest(const NWNXGetStringRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sfunction().empty()) {
    sfunction_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sfunction(), 
      GetArena());
  }
  sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sparam1().empty()) {
    sparam1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sparam1(), 
      GetArena());
  }
  nparam2_ = from.nparam2_;
  // @@protoc_insertion_point(copy_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
}

void NWNXGetStringRequest::SharedCtor() {
sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
nparam2_ = 0;
}

NWNXGetStringRequest::~NWNXGetStringRequest() {
  // @@protoc_insertion_point(destructor:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NWNXGetStringRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  sfunction_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sparam1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NWNXGetStringRequest::ArenaDtor(void* object) {
  NWNXGetStringRequest* _this = reinterpret_cast< NWNXGetStringRequest* >(object);
  (void)_this;
}
void NWNXGetStringRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NWNXGetStringRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NWNXGetStringRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sfunction_.ClearToEmpty();
  sparam1_.ClearToEmpty();
  nparam2_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NWNXGetStringRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string sFunction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_sfunction();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest.sFunction"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sParam1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sparam1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest.sParam1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nParam2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          nparam2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NWNXGetStringRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sfunction().data(), static_cast<int>(this->_internal_sfunction().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest.sFunction");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sfunction(), target);
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sparam1().data(), static_cast<int>(this->_internal_sparam1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest.sParam1");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sparam1(), target);
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_nparam2(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  return target;
}

size_t NWNXGetStringRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sfunction());
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sparam1());
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nparam2());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NWNXGetStringRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NWNXGetStringRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NWNXGetStringRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
    MergeFrom(*source);
  }
}

void NWNXGetStringRequest::MergeFrom(const NWNXGetStringRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sfunction().size() > 0) {
    _internal_set_sfunction(from._internal_sfunction());
  }
  if (from.sparam1().size() > 0) {
    _internal_set_sparam1(from._internal_sparam1());
  }
  if (from.nparam2() != 0) {
    _internal_set_nparam2(from._internal_nparam2());
  }
}

void NWNXGetStringRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NWNXGetStringRequest::CopyFrom(const NWNXGetStringRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXGetStringRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NWNXGetStringRequest::IsInitialized() const {
  return true;
}

void NWNXGetStringRequest::InternalSwap(NWNXGetStringRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  sfunction_.Swap(&other->sfunction_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  sparam1_.Swap(&other->sparam1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(nparam2_, other->nparam2_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NWNXGetStringRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class NWNXSetStringRequest::_Internal {
 public:
};

NWNXSetStringRequest::NWNXSetStringRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
}
NWNXSetStringRequest::NWNXSetStringRequest(const NWNXSetStringRequest& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sfunction().empty()) {
    sfunction_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sfunction(), 
      GetArena());
  }
  sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_sparam1().empty()) {
    sparam1_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_sparam1(), 
      GetArena());
  }
  svalue_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  if (!from._internal_svalue().empty()) {
    svalue_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, from._internal_svalue(), 
      GetArena());
  }
  nparam2_ = from.nparam2_;
  // @@protoc_insertion_point(copy_constructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
}

void NWNXSetStringRequest::SharedCtor() {
sfunction_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
sparam1_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
svalue_.UnsafeSetDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
nparam2_ = 0;
}

NWNXSetStringRequest::~NWNXSetStringRequest() {
  // @@protoc_insertion_point(destructor:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void NWNXSetStringRequest::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  sfunction_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  sparam1_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
  svalue_.DestroyNoArena(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited());
}

void NWNXSetStringRequest::ArenaDtor(void* object) {
  NWNXSetStringRequest* _this = reinterpret_cast< NWNXSetStringRequest* >(object);
  (void)_this;
}
void NWNXSetStringRequest::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void NWNXSetStringRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void NWNXSetStringRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  sfunction_.ClearToEmpty();
  sparam1_.ClearToEmpty();
  svalue_.ClearToEmpty();
  nparam2_ = 0;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* NWNXSetStringRequest::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // string sFunction = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 10)) {
          auto str = _internal_mutable_sfunction();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest.sFunction"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sParam1 = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          auto str = _internal_mutable_sparam1();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest.sParam1"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int32 nParam2 = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          nparam2_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // string sValue = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 34)) {
          auto str = _internal_mutable_svalue();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest.sValue"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* NWNXSetStringRequest::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sfunction().data(), static_cast<int>(this->_internal_sfunction().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest.sFunction");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_sfunction(), target);
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_sparam1().data(), static_cast<int>(this->_internal_sparam1().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest.sParam1");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_sparam1(), target);
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt32ToArray(3, this->_internal_nparam2(), target);
  }

  // string sValue = 4;
  if (this->svalue().size() > 0) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_svalue().data(), static_cast<int>(this->_internal_svalue().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest.sValue");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_svalue(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  return target;
}

size_t NWNXSetStringRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string sFunction = 1;
  if (this->sfunction().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sfunction());
  }

  // string sParam1 = 2;
  if (this->sparam1().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_sparam1());
  }

  // string sValue = 4;
  if (this->svalue().size() > 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_svalue());
  }

  // int32 nParam2 = 3;
  if (this->nparam2() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int32Size(
        this->_internal_nparam2());
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void NWNXSetStringRequest::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const NWNXSetStringRequest* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<NWNXSetStringRequest>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
    MergeFrom(*source);
  }
}

void NWNXSetStringRequest::MergeFrom(const NWNXSetStringRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.sfunction().size() > 0) {
    _internal_set_sfunction(from._internal_sfunction());
  }
  if (from.sparam1().size() > 0) {
    _internal_set_sparam1(from._internal_sparam1());
  }
  if (from.svalue().size() > 0) {
    _internal_set_svalue(from._internal_svalue());
  }
  if (from.nparam2() != 0) {
    _internal_set_nparam2(from._internal_nparam2());
  }
}

void NWNXSetStringRequest::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void NWNXSetStringRequest::CopyFrom(const NWNXSetStringRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:NWNX4.HookHorror.Proto.NWScript.NWNXSetStringRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool NWNXSetStringRequest::IsInitialized() const {
  return true;
}

void NWNXSetStringRequest::InternalSwap(NWNXSetStringRequest* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  sfunction_.Swap(&other->sfunction_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  sparam1_.Swap(&other->sparam1_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  svalue_.Swap(&other->svalue_, &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
  swap(nparam2_, other->nparam2_);
}

::PROTOBUF_NAMESPACE_ID::Metadata NWNXSetStringRequest::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace NWScript
}  // namespace Proto
}  // namespace HookHorror
}  // namespace NWNX4
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest* Arena::CreateMaybeMessage< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest* Arena::CreateMaybeMessage< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest* Arena::CreateMaybeMessage< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest* Arena::CreateMaybeMessage< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest* Arena::CreateMaybeMessage< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest >(arena);
}
template<> PROTOBUF_NOINLINE ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest* Arena::CreateMaybeMessage< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest >(Arena* arena) {
  return Arena::CreateMessageInternal< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
