// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: NWScript/nwnx.proto

#include "NWScript/nwnx.pb.h"
#include "NWScript/nwnx.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace NWNX4 {
namespace HookHorror {
namespace Proto {
namespace NWScript {

static const char* NWNXService_method_names[] = {
  "/NWNX4.HookHorror.Proto.NWScript.NWNXService/NWNXGetInt",
  "/NWNX4.HookHorror.Proto.NWScript.NWNXService/NWNXSetInt",
  "/NWNX4.HookHorror.Proto.NWScript.NWNXService/NWNXGetFloat",
  "/NWNX4.HookHorror.Proto.NWScript.NWNXService/NWNXSetFloat",
  "/NWNX4.HookHorror.Proto.NWScript.NWNXService/NWNXGetString",
  "/NWNX4.HookHorror.Proto.NWScript.NWNXService/NWNXSetString",
};

std::unique_ptr< NWNXService::Stub> NWNXService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< NWNXService::Stub> stub(new NWNXService::Stub(channel));
  return stub;
}

NWNXService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_NWNXGetInt_(NWNXService_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NWNXSetInt_(NWNXService_method_names[1], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NWNXGetFloat_(NWNXService_method_names[2], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NWNXSetFloat_(NWNXService_method_names[3], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NWNXGetString_(NWNXService_method_names[4], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_NWNXSetString_(NWNXService_method_names[5], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status NWNXService::Stub::NWNXGetInt(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest& request, ::NWNX4::HookHorror::Proto::NWScript::Int* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, ::NWNX4::HookHorror::Proto::NWScript::Int, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NWNXGetInt_, context, request, response);
}

void NWNXService::Stub::experimental_async::NWNXGetInt(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Int* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, ::NWNX4::HookHorror::Proto::NWScript::Int, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXGetInt_, context, request, response, std::move(f));
}

void NWNXService::Stub::experimental_async::NWNXGetInt(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Int* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXGetInt_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Int>* NWNXService::Stub::PrepareAsyncNWNXGetIntRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NWNX4::HookHorror::Proto::NWScript::Int, ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NWNXGetInt_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Int>* NWNXService::Stub::AsyncNWNXGetIntRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNWNXGetIntRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NWNXService::Stub::NWNXSetInt(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest& request, ::NWNX4::HookHorror::Proto::NWScript::Void* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NWNXSetInt_, context, request, response);
}

void NWNXService::Stub::experimental_async::NWNXSetInt(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXSetInt_, context, request, response, std::move(f));
}

void NWNXService::Stub::experimental_async::NWNXSetInt(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXSetInt_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Void>* NWNXService::Stub::PrepareAsyncNWNXSetIntRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NWNX4::HookHorror::Proto::NWScript::Void, ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NWNXSetInt_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Void>* NWNXService::Stub::AsyncNWNXSetIntRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNWNXSetIntRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NWNXService::Stub::NWNXGetFloat(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest& request, ::NWNX4::HookHorror::Proto::NWScript::Float* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, ::NWNX4::HookHorror::Proto::NWScript::Float, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NWNXGetFloat_, context, request, response);
}

void NWNXService::Stub::experimental_async::NWNXGetFloat(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Float* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, ::NWNX4::HookHorror::Proto::NWScript::Float, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXGetFloat_, context, request, response, std::move(f));
}

void NWNXService::Stub::experimental_async::NWNXGetFloat(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Float* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXGetFloat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Float>* NWNXService::Stub::PrepareAsyncNWNXGetFloatRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NWNX4::HookHorror::Proto::NWScript::Float, ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NWNXGetFloat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Float>* NWNXService::Stub::AsyncNWNXGetFloatRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNWNXGetFloatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NWNXService::Stub::NWNXSetFloat(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest& request, ::NWNX4::HookHorror::Proto::NWScript::Void* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NWNXSetFloat_, context, request, response);
}

void NWNXService::Stub::experimental_async::NWNXSetFloat(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXSetFloat_, context, request, response, std::move(f));
}

void NWNXService::Stub::experimental_async::NWNXSetFloat(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXSetFloat_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Void>* NWNXService::Stub::PrepareAsyncNWNXSetFloatRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NWNX4::HookHorror::Proto::NWScript::Void, ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NWNXSetFloat_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Void>* NWNXService::Stub::AsyncNWNXSetFloatRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNWNXSetFloatRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NWNXService::Stub::NWNXGetString(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest& request, ::NWNX4::HookHorror::Proto::NWScript::String* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, ::NWNX4::HookHorror::Proto::NWScript::String, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NWNXGetString_, context, request, response);
}

void NWNXService::Stub::experimental_async::NWNXGetString(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest* request, ::NWNX4::HookHorror::Proto::NWScript::String* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, ::NWNX4::HookHorror::Proto::NWScript::String, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXGetString_, context, request, response, std::move(f));
}

void NWNXService::Stub::experimental_async::NWNXGetString(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest* request, ::NWNX4::HookHorror::Proto::NWScript::String* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXGetString_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::String>* NWNXService::Stub::PrepareAsyncNWNXGetStringRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NWNX4::HookHorror::Proto::NWScript::String, ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NWNXGetString_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::String>* NWNXService::Stub::AsyncNWNXGetStringRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNWNXGetStringRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status NWNXService::Stub::NWNXSetString(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest& request, ::NWNX4::HookHorror::Proto::NWScript::Void* response) {
  return ::grpc::internal::BlockingUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_NWNXSetString_, context, request, response);
}

void NWNXService::Stub::experimental_async::NWNXSetString(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXSetString_, context, request, response, std::move(f));
}

void NWNXService::Stub::experimental_async::NWNXSetString(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_NWNXSetString_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Void>* NWNXService::Stub::PrepareAsyncNWNXSetStringRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::NWNX4::HookHorror::Proto::NWScript::Void, ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_NWNXSetString_, context, request);
}

::grpc::ClientAsyncResponseReader< ::NWNX4::HookHorror::Proto::NWScript::Void>* NWNXService::Stub::AsyncNWNXSetStringRaw(::grpc::ClientContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncNWNXSetStringRaw(context, request, cq);
  result->StartCall();
  return result;
}

NWNXService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NWNXService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NWNXService::Service, ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest, ::NWNX4::HookHorror::Proto::NWScript::Int, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NWNXService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest* req,
             ::NWNX4::HookHorror::Proto::NWScript::Int* resp) {
               return service->NWNXGetInt(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NWNXService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NWNXService::Service, ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NWNXService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest* req,
             ::NWNX4::HookHorror::Proto::NWScript::Void* resp) {
               return service->NWNXSetInt(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NWNXService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NWNXService::Service, ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest, ::NWNX4::HookHorror::Proto::NWScript::Float, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NWNXService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest* req,
             ::NWNX4::HookHorror::Proto::NWScript::Float* resp) {
               return service->NWNXGetFloat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NWNXService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NWNXService::Service, ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NWNXService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest* req,
             ::NWNX4::HookHorror::Proto::NWScript::Void* resp) {
               return service->NWNXSetFloat(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NWNXService_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NWNXService::Service, ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest, ::NWNX4::HookHorror::Proto::NWScript::String, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NWNXService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest* req,
             ::NWNX4::HookHorror::Proto::NWScript::String* resp) {
               return service->NWNXGetString(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      NWNXService_method_names[5],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< NWNXService::Service, ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest, ::NWNX4::HookHorror::Proto::NWScript::Void, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](NWNXService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest* req,
             ::NWNX4::HookHorror::Proto::NWScript::Void* resp) {
               return service->NWNXSetString(ctx, req, resp);
             }, this)));
}

NWNXService::Service::~Service() {
}

::grpc::Status NWNXService::Service::NWNXGetInt(::grpc::ServerContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetIntRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Int* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NWNXService::Service::NWNXSetInt(::grpc::ServerContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetIntRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NWNXService::Service::NWNXGetFloat(::grpc::ServerContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetFloatRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Float* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NWNXService::Service::NWNXSetFloat(::grpc::ServerContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetFloatRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NWNXService::Service::NWNXGetString(::grpc::ServerContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXGetStringRequest* request, ::NWNX4::HookHorror::Proto::NWScript::String* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status NWNXService::Service::NWNXSetString(::grpc::ServerContext* context, const ::NWNX4::HookHorror::Proto::NWScript::NWNXSetStringRequest* request, ::NWNX4::HookHorror::Proto::NWScript::Void* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace NWNX4
}  // namespace HookHorror
}  // namespace Proto
}  // namespace NWScript

