// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log.proto

#include "log.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace NWNX4 {
namespace HookHorror {
namespace Proto {
namespace Log {
}  // namespace Log
}  // namespace Proto
}  // namespace HookHorror
}  // namespace NWNX4
static constexpr ::PROTOBUF_NAMESPACE_ID::Metadata* file_level_metadata_log_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_log_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_log_2eproto = nullptr;
const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_log_2eproto::offsets[1] = {};
static constexpr ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema* schemas = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::Message* const* file_default_instances = nullptr;

const char descriptor_table_protodef_log_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\tlog.proto\022\032NWNX4.HookHorror.Proto.Log\032"
  "\033google/protobuf/empty.proto\032\036google/pro"
  "tobuf/wrappers.proto2\203\003\n\nLogService\022=\n\005T"
  "race\022\034.google.protobuf.StringValue\032\026.goo"
  "gle.protobuf.Empty\022=\n\005Debug\022\034.google.pro"
  "tobuf.StringValue\032\026.google.protobuf.Empt"
  "y\022<\n\004Info\022\034.google.protobuf.StringValue\032"
  "\026.google.protobuf.Empty\022<\n\004Warn\022\034.google"
  ".protobuf.StringValue\032\026.google.protobuf."
  "Empty\022;\n\003Err\022\034.google.protobuf.StringVal"
  "ue\032\026.google.protobuf.Empty\022>\n\006LogStr\022\034.g"
  "oogle.protobuf.StringValue\032\026.google.prot"
  "obuf.Emptyb\006proto3"
  ;
static const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable*const descriptor_table_log_2eproto_deps[2] = {
  &::descriptor_table_google_2fprotobuf_2fempty_2eproto,
  &::descriptor_table_google_2fprotobuf_2fwrappers_2eproto,
};
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_log_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_log_2eproto = {
  false, false, 498, descriptor_table_protodef_log_2eproto, "log.proto", 
  &descriptor_table_log_2eproto_once, descriptor_table_log_2eproto_deps, 2, 0,
  schemas, file_default_instances, TableStruct_log_2eproto::offsets,
  file_level_metadata_log_2eproto, file_level_enum_descriptors_log_2eproto, file_level_service_descriptors_log_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_log_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_log_2eproto);
  return descriptor_table_log_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_log_2eproto(&descriptor_table_log_2eproto);
namespace NWNX4 {
namespace HookHorror {
namespace Proto {
namespace Log {

// @@protoc_insertion_point(namespace_scope)
}  // namespace Log
}  // namespace Proto
}  // namespace HookHorror
}  // namespace NWNX4
PROTOBUF_NAMESPACE_OPEN
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
