version: "3"
services:
  nwnx4:
    container_name: nwnx4
    image: nwn2dev/nwnx4:latest
    build:
      context: ..
      dockerfile: ./docker/nwnx4/Dockerfile
    volumes:
      - "${NWNX4_USER_DIR}:/srv/nwnx4-user"
      - "${NWN2_HOME_DIR}:/srv/nwn2-home"
      - "${NWN2_INSTALL_DIR}:/srv/nwn2:ro"
    ports:
      - "${SERVER_PORT:-5121}:5121/udp"
    tty: true
